apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: web
spec:
  containers:
  - name: web-app
    image: <your-ecr-registry>/webapp-assignment2:latest
    ports:
    - containerPort: 80
