apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp-container
        image: <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/webapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-service.mysql-ns.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "db_pass123"
        - name: DATABASE
          value: "employees"
        - name: APP_COLOR
          value: "blue"